USE guestbook;

INSERT INTO messages (name, message) VALUES
('Ana Anić', 'Divan dan za posetu ovom sajtu!'),
('Marko Marković', 'Hvala na odličnom sadržaju, vrlo informativno.'),
('Jovan Petrović', 'Interesantna perspektiva na temu.'),
('Milica Jovanović', 'Da li planirate još članaka na ovu temu?'),
('Petar Petrović', 'Slažem se sa prethodnim komentarom!'),
('Sofija Sofijić', 'Prvi put posjećujem, impresionirana sam.'),
('Nikola Nikolić', 'Ima li neko iskustva sa sličnim problemom?'),
('Elena Elezović', 'Korisne informacije, hvala na deljenju.'),
('Dragan Dragić', 'Ovo je tačno ono što sam tražio!'),
('Mila Milanković', 'Preporučio bih svima da pročitaju ovo.'),
('Ivan Ivanović', 'Da li postoji način da se kontaktirate direktno?'),
('Jelena Jelenić', 'Fantastičan rad, svaka čast autorima!'),
('Stefan Stefanović', 'Nisam siguran da se slažem sa svim tačkama.'),
('Tijana Tijanić', 'Ovo mi je promijenilo pogled na stvari.'),
('Aleksandar Aleksić', 'Tražim slične resurse, imate li preporuka?'),
('Marija Marić', 'Kada možemo očekivati nastavak?'),
('Dejan Dejanović', 'Smatram da je ovo veoma važna tema.'),
('Sanja Sanjić', 'Da li postoji mogućnost saradnje?'),
('Vladimir Vladimirović', 'Hteo bih da podelim svoje iskustvo...'),
('Katarina Katić', 'Ovo je baš ono što mi je trebalo!'),
('Bojan Bojanić', 'Ima li neko još informacija o ovome?'),
('Nina Ninčić', 'Veoma korisno za moj istraživački rad.'),
('Miloš Milošević', 'Da li je ovo dostupno i na drugim jezicima?'),
('Teodora Teodorić', 'Srećom sam naišla na ovaj sadržaj.'),
('Uroš Urošević', 'Kako da primenim ovo u praksi?'),
('Filip Filipović', 'Zanimljiv pristup, nisam ovo ranije video.'),
('Goran Gorić', 'Da li postoji literatura za dalje čitanje?'),
('Hristina Hristić', 'Ovo je promenilo moj način razmišljanja.'),
('Zoran Zorić', 'Smatram da bi ovo trebalo da vidi šira javnost.'),
('Olivera Oliverić', 'Ima li neko slična iskustva?'),
('Predrag Predragović', 'Hvala na detaljnom objašnjenju.'),
('Ružica Ružić', 'Ovo je tačno ono što sam tražila!'),
('Slavica Slavić', 'Veoma korisno za moj projekat.'),
('Đorđe Đorđević', 'Da li možete objasniti još neke detalje?'),
('Željka Željkić', 'Preporučujem svima mojim prijateljima!'),
('Čedomir Čedić', 'Nisam očekivao da ću naći ovako kvalitetan sadržaj.'),
('Šćepan Šćepić', 'Kako da ostanem u toku sa novim objavama?'),
('Ljubica Ljubić', 'Ovo je veoma inspirativno!'),
('Davor Davorić', 'Da li postoji forum za dalju diskusiju?'),
('Branko Brankić', 'Kada će biti nova ažuriranja?');


SELECT * FROM messages;